=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/xsd/Issues.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="issues">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="issue" type="Issue" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Issue">
		<xsd:sequence>
			<xsd:element name="priority-id" type="xsd:int"/>
			<xsd:element name="assignee-id" type="xsd:int" minOccurs="0"/>
			<xsd:element name="type-id" type="xsd:int"/>
			<xsd:element name="status-id" type="xsd:int"/>
			<xsd:element name="summary" type="xsd:string"/>
			<xsd:element name="description" type="xsd:string"/>
			<xsd:element name="project-id" type="xsd:int"/>
			<xsd:element name="build-found" type="xsd:string"/>
			<xsd:element name="create-date" type="xsd:date"/>
			<xsd:element name="created-by-id" type="xsd:int" />
			<xsd:element name="modify-date" type="xsd:date" minOccurs="0"/>
			<xsd:element name="modified-by-id" type="xsd:int" minOccurs="0"/>
			<xsd:element name="resolution-id" type="xsd:int" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/Issues.xml
<?xml version="1.0" encoding="UTF-8"?>
<issues  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Issues.xsd">
	<issue id="1">
		<priority-id>1</priority-id>
		<assignee-id>1</assignee-id>
		<type-id>1</type-id>
		<status-id>1</status-id>
		<summary>bug 0</summary>
		<description>some info about bug 0</description>
		<project-id>1</project-id>
		<build-found-id>1</build-found-id>
		<create-date>2014-04-25</create-date>
		<created-by-id>0</created-by-id>
	</issue>
</issues>
