=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/xsd/Priorities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="priorities">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="priority" type="Priority" minOccurs="4" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Priority">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/Priorities.xml
<?xml version="1.0" encoding="UTF-8"?>
<priorities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Priorities.xsd">
  <priority id="1">
    <name>Critical</name>
  </priority>
  <priority id="2">
    <name>Major</name>
  </priority>
  <priority id="3">
    <name>Important</name>
  </priority>
  <priority id="4">
    <name>Minor</name>
  </priority>
</priorities>
