=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/xsd/Resolutions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="resolutions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="resolution" type="Resolution" minOccurs="4" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Resolution">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/Resolutions.xml
<?xml version="1.0" encoding="UTF-8"?>
<resolutions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Resolutions.xsd">
  <resolution id="1">
    <name>Fixed</name>
  </resolution>
  <resolution id="2">
    <name>Invalid</name>
  </resolution>
  <resolution id="3">
    <name>Wontfix</name>
  </resolution>
  <resolution id="4">
    <name>Worksforme</name>
  </resolution>
</resolutions>
