=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/xsd/Statuses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="statuses">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="status" type="Status" minOccurs="6" maxOccurs="6"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Status">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/Statuses.xml
<?xml version="1.0" encoding="UTF-8"?>
<statuses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Statuses.xsd">
  <status id="1">
    <name>New</name>
  </status>
  <status id="2">
    <name>Assigned</name>
  </status>
  <status id="3">
    <name>In Progress</name>
  </status>
  <status id="4">
    <name>Resolved</name>
  </status>
  <status id="5">
    <name>Closed</name>
  </status>
  <status id="6">
    <name>Reopened</name>
  </status>
</statuses>
