=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/xsd/Users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="users">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="user" type="User" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="User">
		<xsd:sequence>
			<xsd:element name="first-name" type="xsd:string"/>
			<xsd:element name="last-name" type="xsd:string"/>
			<xsd:element name="role" type="xsd:string"/>
			<xsd:element name="email" type="xsd:string"/>
			<xsd:element name="password" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== yurykiryla/issue-tracker/issuetracker/src/main/resources/xml/Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Users.xsd">
	<user id="1">
		<first-name>admin</first-name>
		<last-name>admin</last-name>
		<role>ADMINISTRATOR</role>
		<email>admin</email>
		<password>admin</password>
	</user>
	<user id="2">
		<first-name>user</first-name>
		<last-name>user</last-name>
		<role>USER</role>
		<email>user</email>
		<password>user</password>
	</user>
</users>
